### ISSUE TITLE
Bluepy not installed 

### ISSUE THREAD

**Issue by MysticNynja** [GammaGames/kano-wand-demos#3]
I tired to install this according to the documentation but when I get to the command:

pip3 install -r requirements.txt 

I get the following error:

`Running setup.py install for bluepy ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-hi6vskir/bluepy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-htz0o0o2/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    Working dir is /tmp/pip-install-hi6vskir/bluepy
    execute make -C ./bluepy clean
    execute make -C bluepy -j1
    Failed to compile bluepy-helper. Exiting install.
    Command was 'make -C bluepy -j1' in /tmp/pip-install-hi6vskir/bluepy
    Return code was 2
    Output was:
    b"make: Entering directory '/tmp/pip-install-hi6vskir/bluepy/bluepy'\ntar xzf bluez-src.tgz\ntouch ./bluez-5.47/lib/bluetooth.c ./bluez-5.47/lib/hci.c ./bluez-5.47/lib/sdp.c ./bluez-5.47/lib/uuid.c ./bluez-5.47/attrib/att.c ./bluez-5.47/attrib/gatt.c ./bluez-5.47/attrib/gattrib.c ./bluez-5.47/attrib/utils.c ./bluez-5.47/btio/btio.c ./bluez-5.47/src/log.c ./bluez-5.47/src/shared/mgmt.c ./bluez-5.47/src/shared/crypto.c ./bluez-5.47/src/shared/att.c ./bluez-5.47/src/shared/queue.c ./bluez-5.47/src/shared/util.c ./bluez-5.47/src/shared/io-glib.c ./bluez-5.47/src/shared/timeout-glib.c\nmake: pkg-config: Command not found\nmake: pkg-config: Command not found\ncc -L. -Os -g -Wall  -DHAVE_CONFIG_H -I./bluez-5.47/attrib -I./bluez-5.47 -I./bluez-5.47/lib -I./bluez-5.47/src -I./bluez-5.47/gdbus -I./bluez-5.47/btio -I./bluez-5.47/sys  -o bluepy-helper bluepy-helper.c ./bluez-5.47/lib/bluetooth.c ./bluez-5.47/lib/hci.c ./bluez-5.47/lib/sdp.c ./bluez-5.47/lib/uuid.c ./bluez-5.47/attrib/att.c ./bluez-5.47/attrib/gatt.c ./bluez-5.47/attrib/gattrib.c ./bluez-5.47/attrib/utils.c ./bluez-5.47/btio/btio.c ./bluez-5.47/src/log.c ./bluez-5.47/src/shared/mgmt.c ./bluez-5.47/src/shared/crypto.c ./bluez-5.47/src/shared/att.c ./bluez-5.47/src/shared/queue.c ./bluez-5.47/src/shared/util.c ./bluez-5.47/src/shared/io-glib.c ./bluez-5.47/src/shared/timeout-glib.c \nbluepy-helper.c:33:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/att.c:33:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/gatt.c:32:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/gattrib.c:34:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/utils.c:30:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/btio/btio.c:37:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/src/log.c:38:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/src/shared/io-glib.c:30:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/src/shared/timeout-glib.c:22:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\nmake: *** [Makefile:28: bluepy-helper] Error 1\nmake: Leaving directory '/tmp/pip-install-hi6vskir/bluepy/bluepy'\n"`

`Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-hi6vskir/bluepy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-htz0o0o2/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-hi6vskir/bluepy/`

I then tried to just install bluepy, but I get some managment errors, so just hoping this fixes it :)

Thanks

**Comment by MysticNynja** [comment]
This might have something to do with no permissions for bluepy.  I tried to just run it's bluepy-helper class and get the nomngt error when trying to scan.  I'll go down that thread.

**Comment by GammaGames** [comment]
Oh yeah I think you have to install bluepy as sudo, I think it uses some library that needs elevation

**Comment by MysticNynja** [comment]
I actually tried it with sudo, just forgot to say that.

**Comment by GammaGames** [comment]
Just ran into this, seems like `libglib2.0-dev` is a dependency for the helper tool. You should be able to fix it by running `sudo apt install libglib2.0-dev`.
